"""
lllllllllllccllllllllccclllccccccccccccccccccccccccccccc::ccccccccccccccccc::::::::::;;;;;;;;;:::::::::::::;;;;;;;;,,,,,,,'''''''''''''''''..................'''
llllllllllllllllccllllccllllllllllllccccccccccccccccccccc:::cccccccccccccc::::::::::::;;;;;;;;;;:::::::::;;;;;;;;,,,,,,,,''''''''''''...........................
llllllllllllllllccclllllllcllllllllcccccccccccccccccccc::::::cccccccccccccc:::::::::::;;;;;;;;;::::;;;:;;;;;;;;;;,,,,,,''''''''''''.............................
llllllllllllllllccclllccllccccllccccccccccccccc::cc:::::::cc::ccccc::cccccccccc:::::::;;;;;;;;;::::;;;;;;;;;;;;,,,,,,,,'''''''''''..............................
llllllllllllllllccccccccclccccclccccccccccccccccccc:::::::cccccccccccccccccccccc::::::::;;;;;;;;;;;;;;;;;;;;;;;,,,,,,,''''''''''................................
lllllllllllllcccccccccccccccccccccccccccccccccccccc::::::::cc:::cccccccccccccccccc:::::::::::;;;;;;;;;;;;;;;;;;,,,,,''''''''''''................................
lllllllllllllcccccccccccccccccccccccccccccccccccccc:::::::::c::::cc::cccccccccccccc:::::::,',;;;;;;;;;;;;;;;;;;,,,,,,''''''''''''''.............................
lllllllllllllccccccccccccccccccccccccccllcccccccccc::::::::ccccccc::cccccccccccccccccc:::,..';;;;;;;;;;;;;;;;;;,,,,,,'''''''''''''''............................
llllllllllllllccccccccccccccccccccclccllllccccccccccc::::::cccccccccccccccccccccccc:::::;...';;;;;;;;;;;;,,;;;,,,,,,,,'''''''''''''''...........................
lllllllllllccccccccccccccccccccccccccclllccccccccccccccccccccccccccccccccccccccccccc::::'...,:;;;;;;;;;;;;;;;;;;,,,,,,,'''''''''''''''..........................
lllllllllllccccccccccccccccccccccccccccccccccccllcccccccccccccccccccccccccccccccccccc::,....;;;;;;;;;;;;;;;;;;;;,,,,,,,,,,''''''''''''''........................
llllllllllcccccccccccccccccclccccccccccccccccccllllcccccccccccccccccccccccccccccccc:::'....';:;;;;;;;;,,,,,;;;;;;,,,,,,,,,,,,,,'''''''''........................
llllllllllcccccccccccccccccccccccccccccccccllllllllllllcccccccccccccccccccccccccccc:,......';::;;;;;;,,,,,,,,,;;,,,,,,,,,,,,,'''''''''''........................
lllllllcccccccccllccccccclccllcccccccccclllcllllllllllllllccccccccccccccccccccc::;,,,,'.....;:::;;;;,,,,,,,,,,;;;,,,,;,,,,,,,''''''''''.........................
lllllcccccccccllllccccccccccccccccllllllllllllllllllllllllllccccllllcccccccccc:,....''.......;:::;;;;,,;;,,,,;;;;;;,,,,,;,,,,,'''''''''.........................
llllcccccclllllllccccccccccccccccclllllllllllllllllllllllllllllllllllllllccccc:;''............,:::;;;;;;;;;;;;;;;;;,,,,,,,,,,,,,'''''''.........................
llllcccccllllllllcccccccclllllccllllllllllllllllllllllllllllllloooolllcccc::ccc:;'..'.........,::::;;;;;;;;;,;;;,,,,,,,,,,,,,,,'''''''..........................
llllllccccccclllllccccllcllllllllllllllllllllllllllllllllllllcc::;;;;,,,'.....''...''......';::c::::;;;;;;;;;;;,,,,,,,,,,,,,,,''''''''''........................
lllllllllllccclllllllllllllllllllllllllllllllllllllllllllc::;,,,'',,,,,,''.................:lcccc::::;;;;;;;;;;,,,,,,,,,,,,,,'''''''''''''......................
olllllllllllllllllllllllllllllllllllllllllllllllllllllc;;,,:cclc::::cc;;'..................',;:ccc:::;;;;;;;;;,,,,,,,,,,,,,,'''''''''''''.......................
ooooolllllllllllllllllllllllllllllllllllllllllllllllc:::::;;::::::::;'.........................,;:cc:::::::;;;;;,,,,,,,,,,,,,''''''''''''.......................
oooooolllllllllllllllllllllllllllllllllllllllllllllclddl::,'',,',,'..'''''.......................',::::::::;;;;;,,,,,,,,,,,,,,'''''''''''''.....................
ooooooollllllllllllllllllllllllllllllllllllllccccllccodoll;......'''''''''''''......................,::::::;;;;;;;;,,,,,,,,,,,'',,,'''''''..'...................
oooollllllllllllllllllllllllllllllllllllllll;'',;;,;:::,..............................................,:::::;;;;;;;;,,,,,,,,,,,','''''''''.''...................
ooollllllllllllllcllllllllllllllllllllllllll;.......';:c:'''............................................;:::::;;;;;;;;,,,,,,,,,,,,''''''''......................
oooolllllllllllllllllllllllllllllllllllllc:;,'.....':ldxd;''.............................................,:::::;;;;;;;;;;,,,,,,,'''''''''''.....................
oooollllllllllllllllllllllllllllllllllllc,''..''......','...'',,,'...............................'........';::::;;;;;;;,,,,,,,,,''''''''''''....................
ooooolllllllllllllllllllllllllllllllllll;............',,'''...............................................'';::;;;:;;;,,,,,,,'''''''''''''''....................
ooooollllllllllllllllllllllllllllllc::;;'.......''',,,'',,;;,''...................'.......................'.';:;;;;;;;,,,,,,,''''''''''''''.....................
ooollllllllllllllllllllllllllllll:;'............'',,;;,......................................................,;;;;;;;,,,,,,,,,''''''''''''''....................
ooollllllllllllllllllllllllllll:'...............'''',,,,,,'''.................................................;;;;;;;;,,,,,,,'''''''''''''''....................
ooolllllllccllllllllllllllllll:..............';:clooooooooolcc::,'................',,;;;;;,,'.................';;;;;;;,,,,,,,'''''''''''''''....................
oooollllllccllllllllllllllllll:............':looooddxxxdddxxddolllc;'.........''''cooooooolcc;'...............';;;;;;,,,,,,,'''''''''''''''.....................
doollllllllclllllollllllllllllc'.......,;,;coxxoccllddddooooddollllcclc:;,,:::;:::colooooool:;;,'..............;;;;;;,,,,,,,'''''''''''''''''...................
ddoooooollllllllloollllllllllll:.....':lolcclodddollooooooooddolccllcloooooollcclcloc;clcllc:,;:,..............;;;;;;,,,,,,''''''''''''''''''''.................
dddoooooooooooooooooooolloolllllc,...;llc:cloooodooddddxxxxxddllcccllooooddxddooooldl;;llodl:;::,.............';;;;;;,,,,,,'''''''''''''''''''..................
dddoooooooooooooooooooooooooolllll:'.;l:;cdxxxdddoool::::clccc:cooooddddoddxkkkxxdoo:,:odol:,',;,.............,;;;;;;,,,,,,,''''''''''''''''''..................
dddoooooooooooooooooooooooooooooooooccc;;:;:lodddoooollllllcclolodxkkxkxxdxkkOkxxdol:;:loll::::;;,,,'.........,;;;;;;,,,,,,,,,,,,,,''''''''''''.................
ddddoooooooooooooooooooooooooooooooooolc:;;:codxddodooddxxxxxkkocdkOkkkxdddxxkkxdodolc::cllc::'';;',:;.......';;;;;;;;,,,,,,,,,,,'''''''''''''''................
dddddooooooooooooooooooooloooolllllooolllccloxddddodddxkkkkkkkdlokOOkxdooodddkkxddddol:;::;;;..:dl,';:'......,::;;;;;;;;;,,,,,,,,,,''''''''''''''...............
ddddoooooooooooooooooooolllllllllllloooooloodxdooddddxxxkkkxxxxkkkkkkxocclloxkxxdddol:,,'.';'';ldl,.;;......'::::::;;;;;;;,,,,,,,,,,,,'''''''''''...............
ddddddooooooooooooooooooollllllllllloooooodkkxl:coddxkkxxkkxxkkkxxkkxdoccccloddoooolc;,,,,,..':ll:'';.......,::::::::::;;;;,,,,,,,,,,''''''''''''...............
ddddddoooooooooooooooooooooolllllollllooodxkxoloddl:cdkkxxkkxxxxxxkkxocclllloddddxxxo:;;:l;...,loc,;........,::::::::::;;;;,,,,,,,,,,''''''''''''...............
ddooodddoooooooooooooooooooolllloollllooooddl:;;:cc;'cxkkxxxxxkkOkkxxolllooodxxkkkkxo;,;:::'..,cdl;'........,:::::::::;;;;,,,,,,,,,,,,,''''''''''''.............
ddddodddoooooooooooooooloooooolooooolllooooo:,..,:cccdkxkkkkxdxkkOkxdlcloddddkkkkkxxl,''':c;',:lo:'..........::::::::;;;;;,,,,,,,,,,,,,,,'''''''''''............
dddddoodoooooooooooooolllllooooooooooooooooc::;;codxxkkkkkOOkkkxkkdolc:clodxxkkkkkxd:'..,cl:,:ooc'..........':::::::;;;;;,,,,,,,,,,,,,,,'''''''''.''............
ddddooodoooooooooooooollllloooooooooooooodocccccllodxddxdxkOkkxxxxdlc::clddxxkkkkkdl;'.,,;coodo;.............;c::::::;;;;;;,,,,,,,,,,,,,''''''''...''...........
ddddddooddddooooooooooloooooooooooooooooddoooollloldxxxddddxkkxxxxdolcccodddddxxxddc,.;do::ll;................;::::::::;;;;;,,,,,,,,,,,,,'''''''.'''............
dddddddodddoooooooooollooooooooooooooodxxdlllllccoodxkxxkxoldkkxxxxddocccoddddddddoc,'';:,.....................,:c:::::;;;;,,,,,,,,,,,,,,'''''''..'.............
dddddddddddoooooooooollloooooooooooooodxdooc;;:cccloooddddolloxxxkxxxdc:clodddxdddoc,............................;cc::;;;;;;;,,,,,,,,,,,,,,'''''................
ddddddddddoooooooloolllooooooooooooooodddddoccdkkkkkkxxxxdooooxkkOkkxdlllldxxxxxddl:'.............................';::;;;;;;;,,,,,,,,,,,,,,'''''................
dddddoooooooooooooooooooooooooooooooooooddxdooxkOOOOOOOOOkkkOOkkkOkkxdddooxkxxxdol:,......',,;:::;,,''..............,::;;;;;;;,,,,,,,,,,'''''''.................
ddddoooooodddoooooooooooooooooooooooooooooododxOOOOkkOOkkkOOOOkxxxkkxxddxxkkxdoc:;...',;:clllodxo:;;;,'..............,::::::;;;;;;,,,,,'''''''..................
xddddooooddddoddddooooooooooooooooooooooodddddxOOOOkkkkOOkkkOOkddkOkkxddkxxdo:,,,,;:loddxkkkkkkd:;;;;,''..............;::::::::;;;,,,,''''''''..................
xddddooodddddddddddoooooooooooooooooooooddddddkOOOOOOOOkkkkkkOxoxO0Okxddddo:,,;loodxkOkkOOOkkkklcl:,,,',;,,,;;',,''..,:::::::;;;;,,,,,,''''''...................
xxxxddoddddddddddddooddddoooooooooooooodddddddxkkkOOOOOkxdoooddxO0OOxollc;,;cdxkOOOOOOOkOOOkxdl;,,,:;....';:ldxkdooc;:cc::;;;;;;;;;,,,,''''''...................
xxxxddddddxddddddddddddddddddooooooddddddddddddxxxxxxxxdlc::lxOkkkxdl:;,;:ok000000OOOOOOkxdl;,,,,,::,':;..';:::;,;,,'.;cc:::;;;;;;,,,,,'''''....................
xxxxxdddxxxxxxxddddddddddddddooooooooddodddddoodddoolcc::;;lxkkxxxo:,,;lxO0000OO00OOOkxdcc:,'''.,:c:,:o:....'..........,:c::;;;;;,,,,,,''''.....................
xxxxxxxxxxxxxxxxdddddddddddddooooooodooddoooddoddddddolll:;lddl::;;coxO000OO00OOkkkdlc:;;;,'..',;,',,:c:,'...............,;:;;;,,,,,,'''''......................
kxxxxxxkkkkkkkxxxdddddddddddddoooooddddddoooodddddddxxxdoc;;;;,;cdk0000O000Okxdlllc:;,,,''',,,;,,.';:;:ddollc::;;,,'......',',;,,,,,'''''.......................
kkkkxkkkkkkkkkxxxxddxxdddddddddddddddddddddooddddddxxxxxxdd:,:ok0000000Okxdllc:;;;;,,'....''...''....':oocccccc::::::clc;,,....',,,,''''''......................
kkkkkkkkkkkkxxxxxxxxxxxxxddddddddddddddddddodddddddxxxxxxxdc:oO00000Okxolclc:;,,,''...........':lc::::::,;::;;,,;;;:ccccc;'......'''''''''......................
kkkkkkkkkkkxxxxxxxxxxxxxxxxxdddddddddddddddoooooddxxxxxxxkxllk00Oxdl::cccc:;,,'''.....''',;cll:cc::::clccoxxxdooddddoc:;;:c;'''.....'''''.......................
kkkkkkkkkkxxxxxkxxxxxxxxkkxxxxddddddddddddooooodddxxxxxxxkxoodoc;'',;::,,,,''......',:clcclool:;;:lodoolllooooollccc:;''.............'''''......................
OOkkkkkkkkxxxxxkxxxkxkkkkkkkkxxxxxxddddddddddddddxxxxxxdl:,,;;;'',;;,,,,,,'.....',:llc;;ldo:;,,,,;;;;,,;;;,,;;,,'................''....'''......................
OOkkkkkkkkkxxxxxxxkkkkkkkkkkkkkkkkxxdddddxxdddddxxxxxdl,,'.,:cc:;,,',;,'.'ll'.,:ccc:'.;x00Oxdl::cdkkkkxc;,''''''''.'''..',,,,,;cc:;'....'''.....................
OOkkkkkkkkkkxxxxxkkkkkkkkkkkkkOkkkkxxxxxxxdl:::clc::c:;',;,;;;;,,,;;,....':oocc:;,..'o0K0000OOOkkOOOOOxoolclllddddloolc:loollcclc;'.......'''...................
OOOkkkkkkkkkkkkkkkkkOOOOkkkkkOOkkOkkkxxxxdocccllcc:,''''';:;''';:;'....''';ll;.....;d0000000000OOOOkkxddkkkkxxOOkkddoddllollll:;;,,'............................
OOkkkkkkkkkkkkkkkkOOOOOkkkOOOOOOOOOkkkxxxxxxxdl;,....',;;,'',:c:,...''',:c:,...',,lO0000000000OO0OkxxdoodxkkkdkOOkxdddxdllloollccc:;,........'..................
OOkkkkkkkkkkkkkkkOOOOOOkkOOOOOOOOOOOkkkxxxxdddc'...;::;'..';::,..'''',:l:'...',:cok0000000000OOOOOOkkxxxxxkOOxxkxkkxxxxkkxdxxdooc:col;..........................
OkkkkkkkkkkkkkkkkOOOOOOOOOOOOOOOOOOOkkkxxdddol:;:::c;'...,;;,..,;,'':l:'....,cldOO00000000000OO0OO0OkxkOOkkO0OOOkO0OOkxkkxddddoxdc:ldc,.........................
kkkkkkkkkkkkkkkkOOOOOOOOOOOkkkkkkkkkkxxdddoolllolc:,...';:,',;;,'';ol'......lO0OOOOO00000000OO00OOOOOkOOOOkO0OO0OOK000kkOxxkxddodoccco:'........................
kxxxxxxxxxkkkkkkkkOkkkOOOOkOOkkkkxxxxddddollllll:,...';:;;,;;'.'':o:.......,kK00O000000000K0000OkOOO0O00O0OOK0OOOk00OOkdkxoxxxkxxxo::lc,........................
xddddddddxxxxxkkkkkkkkkkkkOkkkxxxdddddooolcclll:'..';::,,;:c:'.'cl,........,xKK0000000KKKKK00K0O0000OO0OO00O0OxO0OO0kkOdxkdk0xxOddko:llc:,'','..................
ddddddddddxxxxxxxxxkkkkkkkkkxxxddddddooolllcc:,..',cl:,;;,;;;:lol'..........'oO0000KKKK0KKK00000K0KKOO00OK0O00xk0kkOOxkxxOkdOkdxxodkdodxdl:'....................
dddddodddddddxxxxxxxxxxxxxxxdddddddooolllllc;'..';c:,,:;'....;ol..............,cox0K000KKKKK000KKO0K00K00K0xk0xdOOxOOddkxxkddOkkkdoodd:;,.......................
ddddooooooooddxxxxdddddddddoooooooolccllc:;,''';cc;..:c'....,lc...................,ccldddxkOOO0K0O00kOK00KKOk0Odk0OO0Odxkddkdlol;,,.............................
oooooooooollooooooooooooooooooolllcccc:,,,,'',coc,..;c,...';dd'...........................',,;c:;::;;c::odlcloc;:::clc,,,'',....................................
ooooooooollllllllloolllllllooollcccc;'.,;,;:ldd:...;c,...,:dx;..................................................................................................
llooooolllcccccclllllllllllllllccc;'..',,:cdOd,...,lc,';cokOo...............................................................  ..................................
lloollllllccccccclllllllllllllll:'...'';:ldxl,...'colcllldOk;..... .............................................................................................
llllllllcccccccccclccllllllllll;...',,;coxd;.....:xdddolldOx'...................................................................................................
lllclllcccccccccllllccccccccc:'...,,,:ldkd:......oOkkxdoox0d'...................................................................................................
llccllllcccclllllllllcccccc:'. ..,,;:lxOd;......,k0Oxoc:dOOo....................................................................................................
lllllllllccclllllllllccccc:.. ..,;;:oxko,.......:O0koc:;dOOo....................................................................................................
clllllllllccccccllcllcccc;....';,;clxOd,........:kOkxoodOOOo.................................................................   .  .............................
cccccccccccccccccccccccc;. ..';,,:ldOo,..''.....:kOkxxkOOOOd,.................................................................   .. ............................
ccccccccccccccccccccccc;. ..';'':cdOo,..''.....';dOkkOOOOOOkc....................................................................     ..........................
:ccccc::cccccccc::cccc,.  ..,'';lxOo'...'....'',,ckkkOOkkOOkd,..................................................................        ........................
::::::::::c::::cc::cc,. . .,'.;:oko,..........',';dkxkkkkOOkkl'.................................................................        ........................
::::::cc::::::::::c:'. . .,'.,:oxl,............'',lOOkkkkO0Okx:..'...............................................................       ........................
:::::::::::;;;;;;:c;. . .,,';:lxl'...............';dOkxxkOO0Okx:.,cc,..........................................................       . ........................
:::::::::;;,,,,,,::. . .',';clxo'................'';xOxxkkO000Ox:..,cl;...........''..........................................       ...........................
:::::::;;;,,''',;:,. ...'.,:lxd,................''..ckkxxk0OxxkOkc'..,ll;.........'........................................... ... .............................
;;;;;;;;;,''..',;c'.. .'.';col,................,'...'lkkkOOxl,;xOxc,'..:oc....................................................... .......  .....................
,,,,,,''''.....'::.  .'..;:cl,................',.....'lxkOOxolx0Okxc,''.'co;.....................................................     ..  ......................
,,,,,,''.......':;. ....,;co;.................''.......;okkkO000xcclc;,''',cl;.. .................................................  ..... ......................
,''''''........';,. .'.,;co:.....'......................'lkkddol:'.',;;;;;'.;lollc,................................................  .    ......................
'...............;. .'.',;lc.....'.......... .............;oxddc,.......'',,,''';cc:'..................................................... ......................
................;. .'.',::......'........................',,:ol:,'.........',,;;,..''...................................................  ......................
................,.....,;:'.....,'.......................'....,;:::,,'........':,...''.................................................     .....................
................'.....,c:.....',.................'......'.......';:cc;,.....,ol.....'....................................................  .....................
................,',;'.':,.....'..................'.................,;;,,,'..,,...........................................................      .................
................,,,:,'',......'............''...''''....................''',,............................................................       ................
................;c'.::;'......'.............''.',,,,'.''''.'.......    ..................................................................       ................
................,c:,,'.......',..............'.,;,''..''...........         ..............................................................        ..............
................,lodc;''.....',...............';;,'.................                 .....................................................        ..............
................'co:cdl,.....',................',,,'.................                  ...................................................         .............
................,coccdo,.....',.................'''..................                   .................................................  ....     ............
................:loccoc'.....''....:c:;;,........'''..............                       ..................................................  ...      ..........
................:cc:lxl,.....''....cdldkc........,,,..............                  .     ..............................................      ..     ...........
................;:,;oxc.........'lc;:,cl..';.....,,'..............                         ..............................................            ...........
......    ..   .';,,:c,.   .....'cllc,:dlcdd,.........''''........   ...                   ..............................................             ..........
.....    .,,,::;cooool:;;..   ...:,,;',;;':d,.........'''......... ......                    ............................................    ..        .........
.....   .',,;::;locdko;,;,... ...:c:c,;oc:ox;.....''.''''...............                      .............................    ...........            ..........
.....   .''',,;;;;':ol;,.',,.  .....;,'o:.';'........''''.........  ....                       ..............................    .........            ..........
.....       ..;;...'c;..  .........'lc;dx;.......................   ....                       ............................... ....  ..      .. ...   .........._
"""

# https://www.ascii-art-generator.org/ & https://www.reddit.com/r/ColorizedHistory/comments/4kk1z3/otto_von_bismarck_1871/